services:
  web:
    build:
      context: .
      target: ocomon_web
      args:
        TIME_ZONE: ${TIME_ZONE}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        OCOMON_LINK: ${OCOMON_LINK}
        FOLDER_NAME: ${FOLDER_NAME}
    container_name: ocomon_web
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - ocomon_network
  db:
    build:
      context: .
      target: ocomon_db
      args:
        OCOMON_LINK: ${OCOMON_LINK}
        DB_INSTALL: ${DB_INSTALL}
    container_name: ocomon_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --init-file /docker-entrypoint-initdb.d/init.sql
             --default-authentication-plugin=mysql_native_password
    networks:
      - ocomon_network
  cron:
    build:
      context: .
      target: ocomon_cron
      args:
        TZ_CRON: ${TZ_CRON}
    container_name: ocomon_cron
    restart: always
    depends_on:
      - web
    networks:
      - ocomon_network
volumes:
  db_data:

networks:
  ocomon_network:
