services:
  web:
    #volumes:
    #  - ./www:/var/www/html
    build:
      context: .
      target: ocomon_web
    container_name: ocomon_web
    restart: always
    ports:
      - "8081:80"
    environment:
      - DB_HOST=db
      - DB_NAME=ocomon_5
      - DB_USER=ocomon_5
      - DB_PASSWORD=senha_ocomon_mysql
    depends_on:
      - db
    networks:
      - ocomon_network

  db:
    build:
      context: .
      target: ocomon_db
    volumes:
      - db_data:/var/lib/mysql
    container_name: ocomon_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=ocomon_5
      - MYSQL_USER=ocomon_5
      - MYSQL_PASSWORD=senha_ocomon_mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
             --default-authentication-plugin=mysql_native_password
    networks:
      - ocomon_network

volumes:
  db_data:

networks:
  ocomon_network:
