services:
  web:
    build: .
    container_name: ocomon_web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=ocomon
      - DB_USER=ocomon_user
      - DB_PASSWORD=ocomon_password
    depends_on:
      - db
    networks:
      - ocomon_network

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: ocomon_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
      ports:
   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=ocomon
      - MYSQL_USER=ocomon_user
      - MYSQL_PASSWORD=ocomon_password
    networks:
      - ocomon_network

volumes:
  db_data:

networks:
  ocomon_network:
