services:
  web:
    build:
      context: .
      target: ocomon_web
    container_name: ocomon_web
    restart: always
    ports:
      - "8081:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ocomon_network
  db:
    build:
      context: .
      target: ocomon_db
    container_name: ocomon_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --init-file /docker-entrypoint-initdb.d/init.sql
             --default-authentication-plugin=mysql_native_password
    networks:
      - ocomon_network
  cron:
    build:
      context: .
      target: ocomon_cron
    container_name: ocomon_cron
    restart: always
    depends_on:
      - web
    networks:
      - ocomon_network
volumes:
  db_data:

networks:
  ocomon_network:
