# Use a imagem base do MySQL
FROM mysql:5.7

# Defina as variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=ocomon
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponha a porta 3306
EXPOSE 3306
